// tests/patch-android.test.mjs — NGH-BUILD 2026-09-12ae
// Run:  node --test tests/patch-android.test.mjs
//
// capacitor/scripts/patch-android.mjs runs inside the GitHub Actions build,
// between `npx cap add android` and `gradlew`. Nothing else checks it, and
// every way it can go wrong is quiet:
//
//   * a malformed manifest fails the Gradle build with an XML error a long way
//     from the cause;
//   * a missed versionCode stamp is only rejected by Play AFTER the upload
//     finishes, wasting a whole cycle;
//   * a missing CAMERA permission makes the QR scanner silently do nothing on
//     a real phone while working fine in a browser — which is exactly the bug
//     this script was written to fix in 12i.
//
// The script resolves everything relative to its own file, so each test builds
// a throwaway copy of the tree `npx cap add android` produces, drops the real
// script into it, and runs it as the build would.
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCRIPT = path.join(ROOT, 'capacitor', 'scripts', 'patch-android.mjs');

// As generated by Capacitor 8 for this app. Note the INTERNET permission sits
// AFTER </application>, and there is exactly one <activity>.
const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="guru.gamehaven.app.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="\${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
    </application>

    <uses-permission android:name="android.permission.INTERNET" />
</manifest>
`;

const GRADLE = `apply plugin: 'com.android.application'

android {
    namespace "guru.gamehaven.app"
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "guru.gamehaven.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
`;

// Exactly what @capacitor/assets writes into mipmap-anydpi-v26. The <inset> is
// the whole point of the 13b fix: it assumes the source art bleeds to the edge
// and needs insetting into the safe zone, but ours is already cut to that zone,
// so it landed twice and left the logo at 53% of the tile on a real phone.
const CAP_ADAPTIVE = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background>
        <inset android:drawable="@mipmap/ic_launcher_background" android:inset="16.7%" />
    </background>
    <foreground>
        <inset android:drawable="@mipmap/ic_launcher_foreground" android:inset="16.7%" />
    </foreground>
</adaptive-icon>
`;
// The density buckets it fills, at LEGACY icon sizes — 192px at xxxhdpi where a
// 108dp adaptive layer wants 432.
const CAP_DENSITIES = { 'mipmap-ldpi': 36, 'mipmap-mdpi': 48, 'mipmap-hdpi': 72, 'mipmap-xhdpi': 96, 'mipmap-xxhdpi': 144, 'mipmap-xxxhdpi': 192 };
const PNG = (tag) => Buffer.from('\x89PNG\r\n\x1a\n' + tag, 'binary');   // not a real PNG; only identity matters here

// Build a throwaway capacitor/ tree and run the real script inside it.
function run(version = '1.0.0', { manifest = MANIFEST, gradle = GRADLE, noGradle = false, noRes = false, assets = ['icon-foreground.png', 'icon-background.png'] } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap-'));
  const main = path.join(dir, 'android', 'app', 'src', 'main');
  fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
  fs.mkdirSync(main, { recursive: true });
  fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'ngh-app', version }));
  fs.writeFileSync(path.join(main, 'AndroidManifest.xml'), manifest);
  if (!noGradle) fs.writeFileSync(path.join(dir, 'android', 'app', 'build.gradle'), gradle);

  fs.mkdirSync(path.join(dir, 'assets'), { recursive: true });
  for (const a of assets) fs.writeFileSync(path.join(dir, 'assets', a), PNG('SOURCE:' + a));
  if (!noRes) {
    const res = path.join(main, 'res');
    fs.mkdirSync(path.join(res, 'mipmap-anydpi-v26'), { recursive: true });
    for (const f of ['ic_launcher.xml', 'ic_launcher_round.xml']) fs.writeFileSync(path.join(res, 'mipmap-anydpi-v26', f), CAP_ADAPTIVE);
    for (const [d, px] of Object.entries(CAP_DENSITIES)) {
      fs.mkdirSync(path.join(res, d), { recursive: true });
      for (const n of ['ic_launcher_foreground', 'ic_launcher_background', 'ic_launcher', 'ic_launcher_round'])
        fs.writeFileSync(path.join(res, d, n + '.png'), PNG(d + ':' + n + ':' + px));
    }
  }

  // spawnSync, not execFileSync: the latter only hands back stderr when the
  // script EXITS NON-ZERO, so a console.warn from a successful run vanished and
  // no test could assert on it.
  const proc = spawnSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { encoding: 'utf8' });
  const stdout = proc.stdout || '', stderr = proc.stderr || '', status = proc.status;
  const read = (p) => (fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null);
  const res = path.join(main, 'res');
  return {
    dir, status, stdout, stderr, res,
    manifest: read(path.join(main, 'AndroidManifest.xml')),
    gradle: read(path.join(dir, 'android', 'app', 'build.gradle')),
    adaptive: read(path.join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml')),
    adaptiveRound: read(path.join(res, 'mipmap-anydpi-v26', 'ic_launcher_round.xml')),
    // every density copy of a layer that survived, as "<bucket>/<name>"
    layers(name) {
      if (!fs.existsSync(res)) return [];
      return fs.readdirSync(res).filter((d) => fs.existsSync(path.join(res, d, name + '.png'))).sort();
    },
    layerBytes(bucket, name) { const p = path.join(res, bucket, name + '.png'); return fs.existsSync(p) ? fs.readFileSync(p) : null; },
    sourceBytes(asset) { return fs.readFileSync(path.join(dir, 'assets', asset)); },
    rerun() { return run.call(null, version, { manifest: this.manifest, gradle: this.gradle }); }
  };
}

// Gradle will not build a manifest that is not well-formed XML, and the error
// it gives points at the file rather than at us. Parse it here instead.
function xmlIsWellFormed(xml) {
  const f = path.join(os.tmpdir(), 'ngh-manifest-' + Math.random().toString(36).slice(2) + '.xml');
  fs.writeFileSync(f, xml);
  try {
    execFileSync('python3', ['-c', 'import sys,xml.etree.ElementTree as E; E.parse(sys.argv[1])', f], { stdio: 'pipe' });
    return true;
  } catch (e) { return String(e.stderr || e.message); }
  finally { fs.unlinkSync(f); }
}

describe('patch-android.mjs — manifest', () => {
  test('the patched manifest is still well-formed XML', () => {
    const r = run();
    assert.equal(r.status, 0, r.stderr);
    assert.equal(xmlIsWellFormed(r.manifest), true);
  });

  test('App Links land INSIDE the activity, not loose in the application', () => {
    const r = run();
    const act = r.manifest.slice(r.manifest.indexOf('<activity'), r.manifest.indexOf('</activity>'));
    assert.match(act, /autoVerify="true"/, 'an intent-filter outside the activity does nothing at all');
    assert.match(act, /android:host="gamehaven\.guru"/);
  });

  test('every TV QR prefix is covered', () => {
    const r = run();
    for (const p of ['/app/', '/karaoke', '/turns', '/speedgaming', '/mtg']) {
      assert.ok(r.manifest.includes(`android:pathPrefix="${p}"`), 'missing pathPrefix ' + p);
    }
  });

  test('the launcher intent-filter survives', () => {
    const r = run();
    assert.match(r.manifest, /android\.intent\.category\.LAUNCHER/,
      'losing this means no icon in the app drawer');
    assert.equal((r.manifest.match(/android\.intent\.action\.MAIN/g) || []).length, 1);
  });

  test('CAMERA and VIBRATE are declared, camera not required', () => {
    const r = run();
    assert.match(r.manifest, /android\.permission\.CAMERA/, 'the QR scanner silently fails without it (12i)');
    assert.match(r.manifest, /android\.permission\.VIBRATE/, 'turn-tracker haptics');
    assert.match(r.manifest, /<uses-feature android:name="android\.hardware\.camera" android:required="false"/,
      'required="true" would hide the app from tablets with no camera');
  });

  test('INTERNET is not clobbered', () => {
    const r = run();
    assert.match(r.manifest, /android\.permission\.INTERNET/);
  });

  test('running twice changes nothing further — the build re-runs it', () => {
    const once = run();
    const twice = once.rerun();
    assert.equal(twice.status, 0, twice.stderr);
    assert.equal(twice.manifest, once.manifest, 'a second pass must not duplicate the intent-filter');
    assert.equal((twice.manifest.match(/autoVerify/g) || []).length, 1);
    assert.equal((twice.manifest.match(/android\.permission\.CAMERA/g) || []).length, 1);
    assert.match(twice.stdout, /already patched/);
  });
});

describe('patch-android.mjs — version stamping', () => {
  // Play rejects any upload whose versionCode is not higher than the last, and
  // only says so after the upload completes.
  for (const [version, code] of [['1.0.0', 10000], ['1.0.1', 10001], ['1.2.0', 10200], ['2.0.0', 20000], ['1.11.9', 11109]]) {
    test(`${version} → versionCode ${code}`, () => {
      const r = run(version);
      assert.equal(r.status, 0, r.stderr);
      assert.match(r.gradle, new RegExp('versionCode ' + code + '\\b'));
      assert.match(r.gradle, new RegExp('versionName "' + version.replace(/\./g, '\\.') + '"'));
    });
  }

  test('Capacitor\'s hardcoded versionCode 1 is gone', () => {
    const r = run('1.0.0');
    assert.doesNotMatch(r.gradle, /versionCode 1\b/,
      'left at 1, the SECOND Play upload is rejected — after it finishes uploading');
  });

  test('the stamp still runs when the manifest was already patched', () => {
    // The trap this guards: an early `return` on the manifest check would skip
    // the version stamp on every re-run, shipping an unbumped versionCode.
    const first = run('1.0.0');
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap2-'));
    const main = path.join(dir, 'android', 'app', 'src', 'main');
    fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
    fs.mkdirSync(main, { recursive: true });
    fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'ngh-app', version: '1.3.0' }));
    fs.writeFileSync(path.join(main, 'AndroidManifest.xml'), first.manifest);   // already patched
    fs.writeFileSync(path.join(dir, 'android', 'app', 'build.gradle'), first.gradle); // still 10000
    const out = execFileSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { encoding: 'utf8' });
    const g = fs.readFileSync(path.join(dir, 'android', 'app', 'build.gradle'), 'utf8');
    assert.match(out, /already patched/);
    assert.match(g, /versionCode 10300\b/, 'the bump must still apply on a re-run');
  });

  test('a build.gradle with no versionCode fails the build loudly', () => {
    const r = run('1.0.0', { gradle: GRADLE.replace(/versionCode 1\n/, '') });
    assert.notEqual(r.status, 0, 'silently building an unstampable gradle wastes a Play upload');
    assert.match(r.stderr, /versionCode/);
  });

  test('a nonsense version in package.json fails the build loudly', () => {
    const r = run('not-a-version');
    assert.notEqual(r.status, 0);
    assert.match(r.stderr, /1\.2\.3/, 'the error should show the expected shape');
  });

  test('missing android/ at all is a clear error, not a stack trace', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap3-'));
    fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
    fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ version: '1.0.0' }));
    let status = 0, stderr = '';
    try { execFileSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { stdio: 'pipe' }); }
    catch (e) { status = e.status; stderr = String(e.stderr); }
    assert.notEqual(status, 0);
    assert.match(stderr, /cap add android/);
  });
});


describe('patch-android.mjs — the adaptive launcher icon (13b)', () => {
  // Found on a home screen, not in a build log: after 13a made the artwork
  // bigger the icon still looked lost. Decoding the shipped APK turned up an
  // <inset android:inset="16.7%"> around both layers that @capacitor/assets
  // writes and nothing in this repo asked for. It shrinks each layer to 66.6%,
  // and the launcher then shows only the central 72dp of 108dp — another 66.7%.
  // 0.666 x 0.666 put the logo at 52.6% of the tile. Measured on the phone: 54%.

  // The generated file carries a comment explaining why there is no inset, so
  // strip comments before looking for one.
  const markup = (xml) => String(xml).replace(/<!--[\s\S]*?-->/g, '');

  test('the inset @capacitor/assets writes is gone', () => {
    const r = run();
    assert.equal(r.status, 0, r.stderr);
    assert.ok(!/inset/i.test(markup(r.adaptive)), 'the inset is still there:\n' + r.adaptive);
    assert.ok(!/inset/i.test(markup(r.adaptiveRound)), 'the round icon still has the inset');
  });

  test('both layers are still referenced, by both icon variants', () => {
    const r = run();
    for (const [what, xml] of [['ic_launcher', r.adaptive], ['ic_launcher_round', r.adaptiveRound]]) {
      assert.match(xml, /<background android:drawable="@mipmap\/ic_launcher_background"/, what);
      assert.match(xml, /<foreground android:drawable="@mipmap\/ic_launcher_foreground"/, what);
    }
  });

  test('and the XML is well-formed — aapt will not compile it otherwise', () => {
    const r = run();
    assert.equal(xmlIsWellFormed(r.adaptive), true);
    assert.equal(xmlIsWellFormed(r.adaptiveRound), true);
  });

  test('the layer that ships is the exact file the icon tests measure', () => {
    // tests/app-icons.test.mjs measures capacitor/assets/icon-foreground.png.
    // That guarantee is worth nothing unless those bytes are what lands in the
    // APK — @capacitor/assets was resampling them down to 192px first.
    const r = run();
    assert.deepEqual(r.layerBytes('mipmap-xxxhdpi', 'ic_launcher_foreground'), r.sourceBytes('icon-foreground.png'));
    assert.deepEqual(r.layerBytes('mipmap-xxxhdpi', 'ic_launcher_background'), r.sourceBytes('icon-background.png'));
  });

  test('the low-resolution copies are removed, not left to win on some device', () => {
    const r = run();
    for (const layer of ['ic_launcher_foreground', 'ic_launcher_background']) {
      assert.deepEqual(r.layers(layer), ['mipmap-xxxhdpi'],
        layer + ' still has copies in ' + r.layers(layer).join(', '));
    }
  });

  test('the legacy square and round icons are left alone', () => {
    // Those are the pre-API-26 icons, and they are per-density on purpose.
    const r = run();
    assert.ok(r.layers('ic_launcher').length >= 5, 'legacy ic_launcher.png was deleted');
    assert.ok(r.layers('ic_launcher_round').length >= 5, 'legacy ic_launcher_round.png was deleted');
  });

  test('running twice changes nothing', () => {
    const a = run();
    const b = a.rerun();
    assert.equal(b.status, 0, b.stderr);
    assert.equal(b.adaptive, a.adaptive);
    assert.deepEqual(b.layers('ic_launcher_foreground'), ['mipmap-xxxhdpi']);
    assert.ok(!/inset/i.test(markup(b.adaptive)));
  });

  test('a missing source layer fails the build instead of shipping a blank tile', () => {
    const r = run('1.0.0', { assets: ['icon-background.png'] });
    assert.notEqual(r.status, 0, 'the build should have failed');
    assert.match(r.stderr + r.stdout, /icon-foreground\.png/);
  });

  test('no android project is a warning, not a crash', () => {
    const r = run('1.0.0', { noRes: true });
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout + r.stderr, /res\/ not found/);
  });

  test('the version stamp still runs after the icon work', () => {
    // Ordering trap: an early return or a throw in the icon block would skip
    // the versionCode, and Play only rejects that after the upload completes.
    const r = run('1.2.0');
    assert.match(r.gradle, /versionCode 10200/);
  });
});
