// tests/patch-android.test.mjs — NGH-BUILD 2026-09-12ae
// Run:  node --test tests/patch-android.test.mjs
//
// capacitor/scripts/patch-android.mjs runs inside the GitHub Actions build,
// between `npx cap add android` and `gradlew`. Nothing else checks it, and
// every way it can go wrong is quiet:
//
//   * a malformed manifest fails the Gradle build with an XML error a long way
//     from the cause;
//   * a missed versionCode stamp is only rejected by Play AFTER the upload
//     finishes, wasting a whole cycle;
//   * a missing CAMERA permission makes the QR scanner silently do nothing on
//     a real phone while working fine in a browser — which is exactly the bug
//     this script was written to fix in 12i.
//
// The script resolves everything relative to its own file, so each test builds
// a throwaway copy of the tree `npx cap add android` produces, drops the real
// script into it, and runs it as the build would.
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCRIPT = path.join(ROOT, 'capacitor', 'scripts', 'patch-android.mjs');

// As generated by Capacitor 8 for this app. Note the INTERNET permission sits
// AFTER </application>, and there is exactly one <activity>.
const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="guru.gamehaven.app.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="\${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
    </application>

    <uses-permission android:name="android.permission.INTERNET" />
</manifest>
`;

const GRADLE = `apply plugin: 'com.android.application'

android {
    namespace "guru.gamehaven.app"
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "guru.gamehaven.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
`;

// Build a throwaway capacitor/ tree and run the real script inside it.
function run(version = '1.0.0', { manifest = MANIFEST, gradle = GRADLE, noGradle = false } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap-'));
  const main = path.join(dir, 'android', 'app', 'src', 'main');
  fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
  fs.mkdirSync(main, { recursive: true });
  fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'ngh-app', version }));
  fs.writeFileSync(path.join(main, 'AndroidManifest.xml'), manifest);
  if (!noGradle) fs.writeFileSync(path.join(dir, 'android', 'app', 'build.gradle'), gradle);

  let stdout = '', stderr = '', status = 0;
  try {
    stdout = execFileSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    status = e.status; stdout = e.stdout || ''; stderr = e.stderr || '';
  }
  const read = (p) => (fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null);
  return {
    dir, status, stdout, stderr,
    manifest: read(path.join(main, 'AndroidManifest.xml')),
    gradle: read(path.join(dir, 'android', 'app', 'build.gradle')),
    rerun() { return run.call(null, version, { manifest: this.manifest, gradle: this.gradle }); }
  };
}

// Gradle will not build a manifest that is not well-formed XML, and the error
// it gives points at the file rather than at us. Parse it here instead.
function xmlIsWellFormed(xml) {
  const f = path.join(os.tmpdir(), 'ngh-manifest-' + Math.random().toString(36).slice(2) + '.xml');
  fs.writeFileSync(f, xml);
  try {
    execFileSync('python3', ['-c', 'import sys,xml.etree.ElementTree as E; E.parse(sys.argv[1])', f], { stdio: 'pipe' });
    return true;
  } catch (e) { return String(e.stderr || e.message); }
  finally { fs.unlinkSync(f); }
}

describe('patch-android.mjs — manifest', () => {
  test('the patched manifest is still well-formed XML', () => {
    const r = run();
    assert.equal(r.status, 0, r.stderr);
    assert.equal(xmlIsWellFormed(r.manifest), true);
  });

  test('App Links land INSIDE the activity, not loose in the application', () => {
    const r = run();
    const act = r.manifest.slice(r.manifest.indexOf('<activity'), r.manifest.indexOf('</activity>'));
    assert.match(act, /autoVerify="true"/, 'an intent-filter outside the activity does nothing at all');
    assert.match(act, /android:host="gamehaven\.guru"/);
  });

  test('every TV QR prefix is covered', () => {
    const r = run();
    for (const p of ['/app/', '/karaoke', '/turns', '/speedgaming', '/mtg']) {
      assert.ok(r.manifest.includes(`android:pathPrefix="${p}"`), 'missing pathPrefix ' + p);
    }
  });

  test('the launcher intent-filter survives', () => {
    const r = run();
    assert.match(r.manifest, /android\.intent\.category\.LAUNCHER/,
      'losing this means no icon in the app drawer');
    assert.equal((r.manifest.match(/android\.intent\.action\.MAIN/g) || []).length, 1);
  });

  test('CAMERA and VIBRATE are declared, camera not required', () => {
    const r = run();
    assert.match(r.manifest, /android\.permission\.CAMERA/, 'the QR scanner silently fails without it (12i)');
    assert.match(r.manifest, /android\.permission\.VIBRATE/, 'turn-tracker haptics');
    assert.match(r.manifest, /<uses-feature android:name="android\.hardware\.camera" android:required="false"/,
      'required="true" would hide the app from tablets with no camera');
  });

  test('INTERNET is not clobbered', () => {
    const r = run();
    assert.match(r.manifest, /android\.permission\.INTERNET/);
  });

  test('running twice changes nothing further — the build re-runs it', () => {
    const once = run();
    const twice = once.rerun();
    assert.equal(twice.status, 0, twice.stderr);
    assert.equal(twice.manifest, once.manifest, 'a second pass must not duplicate the intent-filter');
    assert.equal((twice.manifest.match(/autoVerify/g) || []).length, 1);
    assert.equal((twice.manifest.match(/android\.permission\.CAMERA/g) || []).length, 1);
    assert.match(twice.stdout, /already patched/);
  });
});

describe('patch-android.mjs — version stamping', () => {
  // Play rejects any upload whose versionCode is not higher than the last, and
  // only says so after the upload completes.
  for (const [version, code] of [['1.0.0', 10000], ['1.0.1', 10001], ['1.2.0', 10200], ['2.0.0', 20000], ['1.11.9', 11109]]) {
    test(`${version} → versionCode ${code}`, () => {
      const r = run(version);
      assert.equal(r.status, 0, r.stderr);
      assert.match(r.gradle, new RegExp('versionCode ' + code + '\\b'));
      assert.match(r.gradle, new RegExp('versionName "' + version.replace(/\./g, '\\.') + '"'));
    });
  }

  test('Capacitor\'s hardcoded versionCode 1 is gone', () => {
    const r = run('1.0.0');
    assert.doesNotMatch(r.gradle, /versionCode 1\b/,
      'left at 1, the SECOND Play upload is rejected — after it finishes uploading');
  });

  test('the stamp still runs when the manifest was already patched', () => {
    // The trap this guards: an early `return` on the manifest check would skip
    // the version stamp on every re-run, shipping an unbumped versionCode.
    const first = run('1.0.0');
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap2-'));
    const main = path.join(dir, 'android', 'app', 'src', 'main');
    fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
    fs.mkdirSync(main, { recursive: true });
    fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'ngh-app', version: '1.3.0' }));
    fs.writeFileSync(path.join(main, 'AndroidManifest.xml'), first.manifest);   // already patched
    fs.writeFileSync(path.join(dir, 'android', 'app', 'build.gradle'), first.gradle); // still 10000
    const out = execFileSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { encoding: 'utf8' });
    const g = fs.readFileSync(path.join(dir, 'android', 'app', 'build.gradle'), 'utf8');
    assert.match(out, /already patched/);
    assert.match(g, /versionCode 10300\b/, 'the bump must still apply on a re-run');
  });

  test('a build.gradle with no versionCode fails the build loudly', () => {
    const r = run('1.0.0', { gradle: GRADLE.replace(/versionCode 1\n/, '') });
    assert.notEqual(r.status, 0, 'silently building an unstampable gradle wastes a Play upload');
    assert.match(r.stderr, /versionCode/);
  });

  test('a nonsense version in package.json fails the build loudly', () => {
    const r = run('not-a-version');
    assert.notEqual(r.status, 0);
    assert.match(r.stderr, /1\.2\.3/, 'the error should show the expected shape');
  });

  test('missing android/ at all is a clear error, not a stack trace', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ngh-cap3-'));
    fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
    fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'patch-android.mjs'));
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ version: '1.0.0' }));
    let status = 0, stderr = '';
    try { execFileSync(process.execPath, [path.join(dir, 'scripts', 'patch-android.mjs')], { stdio: 'pipe' }); }
    catch (e) { status = e.status; stderr = String(e.stderr); }
    assert.notEqual(status, 0);
    assert.match(stderr, /cap add android/);
  });
});
